### ISSUE TITLE
android 9 崩溃。

### ISSUE THREAD

**Issue by 451518849** [marekchen/flutter_qq#7]
android 9 QQ登录不可用。
error log:
W/System.err(13816): java.lang.ClassNotFoundException: com.tencent.stat.StatConfig
W/System.err(13816): 	at java.lang.Class.classForName(Native Method)
W/System.err(13816): 	at java.lang.Class.forName(Class.java:453)
W/System.err(13816): 	at java.lang.Class.forName(Class.java:378)
W/System.err(13816): 	at com.tencent.connect.a.a.c(ProGuard:58)

**Comment by marekchen** [comment]
这不是崩溃的地方

**Comment by 451518849** [comment]
嗯，如何解决？

**Comment by marekchen** [comment]
你首先要找到崩溃点的log啊

**Comment by 451518849** [comment]
没有崩溃点，调QQ的时候程序直接挂掉，然后显示这个error。

**Comment by ylytddd** [comment]
> 没有崩溃点，调QQ的时候程序直接挂掉，然后显示这个error。

我的也闪退
log是: 
`Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.conn.scheme.SchemeRegistry"`

找到解决方案: 
https://www.jianshu.com/p/ea3c189f04d0

你看看是不是和你的一样
